trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
  paths:
    exclude:
      - README.md
      - LICENSE

variables:
  group: 'pipelines'
  stagingCluster: 'iofogctl-ci'
  stagingClusterRegion: 'us-central1-a'
  repository: 'focal-freedom-236620/iofogorg'
  buildTag: $(Build.BuildId)
  branchTag: $(Build.SourceBranchName)

jobs:
  - job: "ioFog"
    pool:
      vmImage: 'Ubuntu-22.04'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
        displayName: 'npm install'

      - script: |
          npm run build
        displayName: 'npm build'

      - task: Docker@2
        displayName: 'build docker'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'build'
          Dockerfile: "Dockerfile"
          tags: |
            $(buildTag)
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - task: Docker@2
        displayName: 'push docker'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'push'
          Dockerfile: "Dockerfile"
          tags: |
            $(buildTag)
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - task: DownloadSecureFile@1
        displayName: 'Download secure file'
        inputs:
          secureFile: 'azure-gcp.json'
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - bash: |
          set -e
          keyFilePath="$(Agent.TempDirectory)/azure-gcp.json"
          CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"

          echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
          gcloud components list

          gcloud --quiet auth activate-service-account --key-file="${keyFilePath}"
          gcloud --quiet config set project focal-freedom-236620
          gcloud --quiet container clusters get-credentials $(stagingCluster) --region $(stagingClusterRegion)
          gcloud --quiet auth configure-docker
        displayName: 'set up gcloud'
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - bash: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
        displayName: 'set up kubectl'
        condition: ne(variables['Build.Reason'], 'PullRequest')

      - bash: |
          sed "s/{{BUILD_NUMBER}}/$(buildTag)/g" "deploy/staging.yaml" | ./kubectl apply -f -
        displayName: 'update deployment'
        condition: ne(variables['Build.Reason'], 'PullRequest')
